force-app/main/default/objects/Dataflow_Job_Failure__e/Dataflow_Job_Failure__e.object-meta.xml
<CustomObject>
    <label>Dataflow Job Failure</label>
    <pluralLabel>Dataflow Job Failures</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>The date that the job was created / scheduled.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>How long the job ran for.</description>
    <label>Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date-time that the job finished.</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/ExecutedDate__c.field-meta.xml
<CustomField>
    <fullName>ExecutedDate__c</fullName>
    <description>The date-time the job began processing.</description>
    <label>Executed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The name / label of the recipe or dataflow.</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Detailed message about the job&apos;s status or failure.</description>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/NextRunDate__c.field-meta.xml
<CustomField>
    <fullName>NextRunDate__c</fullName>
    <description>The date-time the job is next scheduled, if available.</description>
    <label>Next Run Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>The % completion of the job.</description>
    <label>Progress</label>
    <precision>11</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <description>How many times the job was retried.</description>
    <label>Retry Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date-time that the job was taken off the queue.</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Known values:
Failure
Queued
Running
Success
Warning</description>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Dataflow or Recipe.</description>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataflow_Job_Failure__e/fields/Wait_Time__c.field-meta.xml
<CustomField>
    <fullName>Wait_Time__c</fullName>
    <description>How long the job waited to execute after being dequeued.</description>
    <label>Wait Time</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/DataflowJobHistory__c.object-meta.xml
<CustomObject>
    <label>Dataflow Job History</label>
    <nameField>
        <label>Dataflow Job History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dataflow Job History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DataflowJobHistory__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/ExecutedDate__c.field-meta.xml
<CustomField>
    <fullName>ExecutedDate__c</fullName>
    <label>Executed​Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/JobType__c.field-meta.xml
<CustomField>
    <fullName>JobType__c</fullName>
    <label>JobType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/NextRunDate__c.field-meta.xml
<CustomField>
    <fullName>NextRunDate__c</fullName>
    <label>Next​Run​Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <label>Progress</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <label>Retry​Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DataflowJobHistory__c/fields/WaitTime__c.field-meta.xml
<CustomField>
    <fullName>WaitTime__c</fullName>
    <label>WaitTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnalyticsMonitor.cls
public class AnalyticsMonitor implements Schedulable{

    //String schedule = '0 30 * * * ?';//every 30 mins
    //System.Schedule('FetchDataflowJobDetails',schedule,new AnalyticsMonitor());

    public static void execute(SchedulableContext SC){
        AnalyticsMonitor.getJobs();
    }

    @future(callout=true)
    public static void getJobs(){
        
		String restApi = URL.getSalesforceBaseUrl().toExternalForm() + '/services/data/v57.0/wave/dataflowjobs';
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('GET');
        httpRequest.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionID());
        httpRequest.setHeader('Content-Type', 'application/json; charset=UTF-8');
        httpRequest.setHeader('Accept', 'application/json');
        httpRequest.setEndpoint(restApi);
        
        
        DataflowJobList jobs = new DataflowJobList();

        try {  
			Http http = new Http();   
            HttpResponse httpResponse = http.send(httpRequest);
            jobs = (DataflowJobList)System.JSON.deserialize(httpResponse.getBody(), DataflowJobList.class);
            AnalyticsMonitor.processJobs(jobs);
        } catch( System.Exception e) {
            System.debug(LoggingLevel.ERROR, 'ERROR: '+ e);
            throw e;
        }
    }

    public static void processJobs(DataflowJobList jobs){
        List<DataflowJobHistory__c> dfJobHistList = new List<DataflowJobHistory__c>();
        List<Dataflow_Job_Failure__e> dfJobFailure = new List<Dataflow_Job_Failure__e>();
        for (DataflowJobList.DataflowJob dfj :jobs.dataflowJobs){
            if(dfj.status == 'Failure' || dfj.status == 'Success' || dfj.status == 'Warning'){
                dfJobHistList.add(new DataflowJobHistory__c(
                    Id__c = dfj.id,
                    createdDate__c = dfj.createdDate,
                    duration__c = dfj.Duration,
                    EndDate__c = dfj.endDate,
                    ExecutedDate__c = dfj.executedDate,
                    Label__c = dfj.label,
                    Message__c = dfj.message,
                    NextRunDate__c = dfj.nextRunDate,
                    Progress__c = dfj.progress,
                    RetryCount__c = dfj.retryCount,
                    StartDate__c = dfj.startDate,
                    Status__c = dfj.status,
                    Type__c = dfj.type,
                    WaitTime__c = dfj.waitTime,
                    JobType__c = dfj.jobType
                ));
                //klaxon
                if (dfj.status=='Failure'){
                    dfJobFailure.add(new Dataflow_Job_Failure__e(
                        createdDate__c = dfj.createdDate,
                        duration__c = dfj.Duration,
                        EndDate__c = dfj.endDate,
                        ExecutedDate__c = dfj.executedDate,
                        Label__c = dfj.label,
                        Message__c = dfj.message,
                        NextRunDate__c = dfj.nextRunDate,
                        Progress__c = dfj.progress,
                        Retry_Count__c = dfj.retryCount,
                        StartDate__c = dfj.startDate,
                        Status__c = dfj.status,
                        Type__c = dfj.type,
                        Wait_Time__c = dfj.waitTime
                    ));
                }
            }
        }

        //save history
        List<Database.UpsertResult>  dbsr;
        try {
            dbsr = Database.upsert(dfJobHistList,DataflowJobHistory__c.Id__c,false);
        } catch (System.DMLException e){
            for (Database.UpsertResult sr : dbsr) {
                    for(Database.Error err : sr.getErrors()) {
                        //logging needed
                    }
            }
            throw e;
        }

        //publish failures
        List<Database.SaveResult>  edbsr;
        try {
            edbsr = EventBus.publish(dfJobFailure);
        } catch (System.DMLException e){
            for (Database.SaveResult sr : edbsr) {
                    for(Database.Error err : sr.getErrors()) {
                        //logging needed
                    }
            }
            throw e;
        }
            
    }

    public static void restartJob(){

    }
}